# Generated by Django 2.1.7 on 2019-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_access_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=312, unique=True),
            preserve_default=False,
        ),
    ]
